version: '3.9'

services:
  pg:
    image: bitnami/postgresql:latest
    networks:
      - app_network
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=upload
      - POSTGRESQL_PERFORM_RESTORE=true
    volumes:
       - './docker:/docker-entrypoint-initdb.d'

networks:
  app_network:
    driver: bridge
